### ISSUE TITLE
Question: Is it safe to share a client instance with other concurrent tasks?

### ISSUE THREAD

**Issue by cakoose** [NodeRedis/node-redis#1522]
My Node server handles multiple concurrent requests.  I'm planning on creating a single process-wide client instance at startup and using it everywhere.

For that to be safe, I created a more limited interface that doesn't allow `.on(...)`, `.quit()`, `.auth()`, any blocking commands (e.g. `blpop()`), or `watch()`.

I'm not sure about `multi()`, though.  The Redis `MULTI` command affects the connection state, which makes it unsafe to use on a shared connection.  However, it looks like node-redis queues up everything in a transaction and only sends them all together when `Multi#exec()` is called.  That makes me believe that it is safe to use `multi()` on a shared client instance.

Does that sound right?  Is there anything else I should watch out for when sharing a client instance?  Thanks!

**Comment by stockholmux** [comment]
You are correct. `client.multi()` in this module creates a queue in node, any subsequent commands are then pushed on to this queue. Once you run `client.exec()` all the commands are pipelined to Redis. So, it is safe when you're dealing with a shared connection to Redis. (This is actually how almost all clients work across other languages too).

What you are describing is a pretty common best practice - most people don't bother limiting the interface and just reply upon convention in the code (although I get your desire to do this).  

The only other things to watch out for if you want to be safe would be to prevent subscriptions (`client.subscribe`) and commands that block via arguments (`xread`...`block`). It's possible to execute many of these things with `client.send_command`, so that's another one to possibly prevent. 

Finally, to be honest, you may want to think about this laterally and create an interface that allows these (very useful) commands if the connection is duplicated (`client.duplicate`). 

I'm going to close this as it's not really an issue to fix, but feel free to continue to ask questions.
