### ISSUE TITLE
WRONGPASS invalid username-password pair

### ISSUE THREAD

**Issue by leobeosab** [NodeRedis/node-redis#1591]
### Issue
Hi, I wish I had more time to fill this out but I'm making this for others who are having this issue. Our Node applications started crashing on startup when we updated (without realizing) to 3.1.0. Thankfully this only happened on our stage servers so no harm was done! But hopefully, others find this helpful! 

The error is as follows
```
ReplyError: WRONGPASS invalid username-password pair
    at parseError (redacted.../node_modules/redis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (redacted.../node_modules/redis/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'AUTH',
  args: [ 'redacted', 'redacted' ],
  code: 'WRONGPASS'
}
```

The username-password pair is correct and works before 3.1.0 to fix this for now we downgraded to 3.0.2

---

### Environment

 - **Node.js Version**: 14.15.4
 

 - **Redis Version**: Unkown (I can add once I find out)
 

 - **Platform**: MacOS 11.0.1, Heroku Node, Arch Linux

**Comment by darklight147** [comment]
UP, i can confirm that this issue exists an encountered it just now, trying to connect to my remote redis database

**Comment by leibale** [comment]
@lebseu @darklight147 are you using the default user or a custom ACL user?
If you're using the default user, make sure the set the username to "default" or just leave it empty.

**Comment by darklight147** [comment]
@leibale resolved issue by reverting to version 3.0.2, although this would work for a higher version expect latest, am using this code to connect to my remote redis db:

```ts
export const redisClient = redis.createClient({
	url: redisUri,
});
```

my redisUri is formated this way: redis://username:password@host-domain:15601

**Comment by leibale** [comment]
@darklight147 try to change the "username" part to "default"

**Comment by darklight147** [comment]
@leibale that can't be right, because those are the credentials to my database

**Comment by leibale** [comment]
@darklight147 until version 3.1.0 the username part was ignored, so please try to set it to "default" (or leave it empty) and check if that's help

**Comment by bamse16** [comment]
I have the same issue as @darklight147. Setting the username to `redis://default:password@ip` or empty string `redis://:password@ip` does not help.

The only thing that helps is setting the connection string as `redis://password@ip`, no `username:` part.

When a username is present, even if named `default`, the auth command is sent as `auth  'default', 'password'` and redis 3.0.6 rejects that.

**Comment by darklight147** [comment]
@bamse16 3.0.2 works fine for now, give it a shot

**Comment by bamse16** [comment]
Thanks @darklight147. Forgot to mention that 3.0.2 works for me as well. I'm trying to get the latest version to work.

**Comment by leibale** [comment]
I tried reproducing it with
```bash
redis-server --requirepass password
```
```javascript
require('redis').createClient('redis://:password@localhost:6379');
```
and it fired an AUTH command with only 1 argument (the password).

@leobeosab @darklight147 @bamse16 I would like to debug it with one of you, because I couldn't reproduce it

**Comment by bamse16** [comment]
I've tried `redis://:password@localhost:6379` and that works for me as well. Previously, a package that was parsing the URI would not handle empty username, so that was not related to this package.

**Comment by nbasili** [comment]
Heroku deployments are broken at `3.1.0`, initializing the client using:

```
require('redis').createClient(process.env.REDIS_URL)
```

where `REDIS_URL` is set automatically by Heroku using the format `redis://h:<password>@<host>:<port>`

The error is:

```
Uncaught ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
```

This renders the latest version unusable on Heroku, everything is working fine at `3.0.2` though.

**Comment by gkorland** [comment]
@bamse16 using `redis://:password@localhost:6379` should do the trick. 
@nbasili you should try without the username `h` --> `redis://:<password>@<host>:<port>`

**Comment by neemah** [comment]
So the 3.1.0 breaking production for many users due to it stopped supporting URL with a username.

Is  this something needed to be mentioned in the changelog or is there a fix to, for example, ignore username in the URL so this won't be a matter? :-)

**Comment by jonabantao** [comment]
We're having this issue as well. Like others said, 3.0.2 resolves it for us. 
We're reading the redis connection string from whatever the cloud environment gives us, which for right now is `rediss://<username>:<password>@<ip>:<port>`

The error we got was '_wrong number of arguments for 'auth' command_'.

**Comment by eiskalteschatten** [comment]
We're also having this issue. And yes, it broke production. I don't want to remove the username because we are hosting with Heroku which automatically manages the Redis connection URL.

**Comment by martianboy** [comment]
We just encountered the same issue, fortunately on the staging server. Shouldn't it have been a major version change? I just ran `npm update` and boom everything broke.

**Comment by lchrennew** [comment]
I encountered the same issue when upgrade to 4.27.1.
4.27.0: the same issue
4.26.0: issue not exists.
 Downgrade to  4.26.0 works.

@leibale

**Comment by sojournerc** [comment]
+1 - Like @eiskalteschatten we use the heroku redis add-on so the URL is managed by them. 

I'm not inclined to create a brittle solution of modifying the URL to remove the username at runtime. 

This really should've been mentioned in the release notes.

**Comment by leibale** [comment]
@sojournerc it is maintained in the release of [v3.1.0](https://github.com/NodeRedis/node-redis/releases/tag/v3.1.0).
can you please share the exact add-on and version you're using? cause I've tried reproducing it with both [Heroku Redis](https://elements.heroku.com/addons/heroku-redis) & [Redis Enterprise Cloud](https://elements.heroku.com/addons/rediscloud), and in both the url in the env is without a username.

**Comment by sojournerc** [comment]
thanks @leibale

versions are: 
node-redis: 3.1.1
redis: 4.0 , which is an older version (we are about to upgrade) so Heroku likely not longer provisions new instances with that version since it's nearing end of life.

**Comment by H4kor** [comment]
For anyone with an old redis installation on Heroku, this will solve the issue (node-redis 3.1.2):

```
                const url = new URL(process.env.REDIS_URL);
                const client = redis.createClient(Number.parseInt(url.port), url.hostname, {
                    auth_pass: url.password
                });
```

**Comment by RicardoOliveiraa** [comment]
> @darklight147 try to change the "username" to "default"

Maan, thank you so muuuuch

**Comment by huineng** [comment]
just installed the latest version 4.0.0
using 

"URI": "rediss://password@url:port   did not work
"URI": "rediss://default:password@url:port   did not work
"URI": "rediss://admin:password@url:port   did not work

"URI": "rediss://:password@url:port   did work   just putting : before password

is this the new behaviour ?

**Comment by RicardoOliveiraa** [comment]
It’s a new behaviour, now you should use it like this “URI”: ***@***.***:port”

Probably isn’t working cause you misspelled redis in your url, using two s.

Hope it solves your problem =D

________________________________
De: Guy Huinen ***@***.***>
Enviado: Thursday, November 25, 2021 7:24:40 AM
Para: redis/node-redis ***@***.***>
Cc: RicardoOliveiraa ***@***.***>; Comment ***@***.***>
Assunto: Re: [redis/node-redis] WRONGPASS invalid username-password pair (#1591)


just installed the latest version 4.0.0
using

"URI": ***@***.***:port did not work
"URI": ***@***.***:port did not work
"URI": ***@***.***:port did not work

"URI": ***@***.***:port did work just putting : before password

is this the new behaviour ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fredis%2Fnode-redis%2Fissues%2F1591%23issuecomment-979068049&data=04%7C01%7C%7C61297d528c7f4030739e08d9affdcab7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734326837982192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gBO6APInwG39%2FYQh3KXzryYYswNm9OIxoOfM6uXYer8%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJD27W23HQCPX43X7CWDSWLUNYFGRANCNFSM42F4RDGA&data=04%7C01%7C%7C61297d528c7f4030739e08d9affdcab7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734326837982192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8iWQvAq7ByBnLH9OoqLuARWO%2BmtH%2BjkYYmCQpAeRoNo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C61297d528c7f4030739e08d9affdcab7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734326837992140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=svhSSg1GBIhy%2B%2BQwFxY%2BM4ED8Df0Gj2o2v1M%2BjRebqM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C61297d528c7f4030739e08d9affdcab7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637734326837992140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7P9rKk%2F5zqEDULi3UlDR%2BfuxGS%2B6aMJColi5bfzGhHo%3D&reserved=0>.

**Comment by huineng** [comment]
rediss with 2 ss is for an encrypted connection.  and again it works for me just putting the :

**Comment by leibale** [comment]
@huineng @RicardoOliveiraa I haven't noticed this breaking change (in v3 if only one parameter was sent it was used as the password, in v4 it'll be used as the username), I'm not too sure if I'll "fix" it or just add it into the change log.

**Comment by jdgamble555** [comment]
`npm i redis` - the other js versions don't seem to work correctly

**Comment by lvzenglei** [comment]
> 
That is so great!!!!!  It saved me~~~~~

**Comment by mouday** [comment]
why not use 'root:123456' ?

**Comment by revskill10** [comment]
@leibale You're Redis magician ?

**Comment by leibale** [comment]
@revskill10 I'm trying... :)

**Comment by 0xankit** [comment]
> just installed the latest version 4.0.0 using
> 
> "URI": "rediss://password@url:port did not work "URI": "rediss://default:password@url:port did not work "URI": "rediss://admin:password@url:port did not work
> 
> "URI": "rediss://:password@url:port did work just putting : before password
> 
> is this the new behaviour ?

In my case:
`self.redis_client = Redis(
            host=settings.REDIS_HOST, port=settings.REDIS_PORT,
            db=settings.REDIS_DB, password=settings.REDIS_PASSWORD,
            socket_timeout=5)` : worked
while:
`self.redis_client = Redis(
            host=settings.REDIS_HOST, port=settings.REDIS_PORT,
            db=settings.REDIS_DB, password=settings.REDIS_PASSWORD,
            username=settings.REDIS_USERNAME, socket_timeout=5)` was giving `invalid username-password pair`

**Comment by FelipeDeveloperFullStack** [comment]
> just installed the latest version 4.0.0 using
> 
> "URI": "rediss://password@url:port did not work "URI": "rediss://default:password@url:port did not work "URI": "rediss://admin:password@url:port did not work
> 
**> "URI": "rediss://:password@url:port did work just putting : before password**
> 

Thank you so much. 👍

**Comment by ashgkwd** [comment]
Interesting; how active this thread is. I have 2 Redis instances on two different boxes. I see this WRONGPASS issue in one but not the other one.

Version info from `apt show redis`

```
Package: redis
Version: 5:7.0.15-1build2
Priority: optional
Section: universe/database
Origin: Ubuntu
```

🫱  One box I use for syncing ActionCable (Rails) that is configured to have noeviction. Here URL with `:` before the password and blank username work. Example: `redis://:password@host:port/1`

🫱 Another box is used for caching (with allkeys-lfu), there, a URL with username `default` works. Example: `redis://default:password@host:port/1`

**Comment by mendiu** [comment]
for someone who ended up here lately... Check the docker network, I had this issue because the service redis was pointing a different redis docker container that I expected.

Good luck

**Comment by YunarW** [comment]
I encountered the same issue. Every time I entered the command 127.0.0.1:6379> AUTH MyPassword123, I received an "invalid username-password pair" error. Later, I discovered that at the end of the Redis configuration file, there was a requirepass RandomPassword entry, which overrode my earlier requirepass MyPassword123 setting.

**Comment by jason-greenberg** [comment]
I had this issue and noticed I had a newline character at the end of the password, which was stored in a cloud secret manager. Removing the newline fixed the problem for me 🤦‍♂
