### ISSUE TITLE
v4: Should send bytes instead of UTF-16 length

### ISSUE THREAD

**Issue by MCPE-PC** [NodeRedis/node-redis#1628]
### Issue

> Describe your issue here

For Node Redis v4, the code seems to be using `String.prototype.length` to calculate the byte length of an argument to load on the payload
https://github.com/NodeRedis/node-redis/blob/c72aab2fc29a9cc994f6b810aeb10a4fe1863f29/lib/commands-queue.ts#L52-L53
It should load the byte length instead. `Buffer.byteLength(String.prototype)` is one of its ways.

---

### Environment

 - **Node.js Version**: `16.0.0`
 

 - **Redis Version**: `6.2.4`
 

 - **Platform**: `Linux MCPEPC-DESKTOP 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by NovaAtWarren** [comment]
As per [https://github.com/NodeRedis/node-redis/pull/1630#issuecomment-881964033](this comment), it seems to be working correctly already. Thank you still, though, because (if the test gets merged) we'll know if it breaks.

**Comment by MCPE-PC** [comment]
Probably it is not working correct, [here](https://github.com/NodeRedis/node-redis/pull/1630#pullrequestreview-708984050). I was testing the v4 and encountered wrong bytes issue on Redis. Small patching of using `Buffer.byteLength()` fixed it perfectly.

**Comment by NovaAtWarren** [comment]
Turns out there were two places that calculated the length of a string
[https://github.com/NodeRedis/node-redis/blob/c72aab2fc29a9cc994f6b810aeb10a4fe1863f29/lib/commands-queue.ts#L47](here)
and
[https://github.com/NodeRedis/node-redis/blob/c72aab2fc29a9cc994f6b810aeb10a4fe1863f29/lib/commands-queue.ts#L53](here)

The fix you wrote worked perfectly fine, I just didn't encounter it because I put the special character in the wrong place to encounter the specific issue you did.

Thank you for the help, re-opening PR for review and merging.

**Comment by MCPE-PC** [comment]
@NovaAtWarren Cool. But what if the type of the original argument is ArrayBuffer view? Let's see,
https://github.com/nodejs/node/blob/eaca13ddc9092e831b9b45180c6e0ee1f3292e5e/src/node_buffer.cc#L698
Here, `Buffer.byteLength()` with the `string` typed argument is slower than the one with the ArrayBuffer view argument (it has `byteLength` property by design, i. e. `Buffer.from(str).byteLength`)

I'd like to suggest some changes to your PR(#1630).

**Comment by leibale** [comment]
@MCPE-PC good catch, thanks
